// Generated by scripts/generate-agent-context.mjs. Do not edit manually.

import type { AgentContextData } from "./agentContextTypes.js";

export const GENERATED_AGENT_CONTEXT = {
	"schemaVersion": 1,
	"modes": [
		{
			"id": "mcp",
			"title": "HISE MCP documentation bridge",
			"summary": "Call the HISE MCP documentation server through hise-cli when native MCP access is unavailable.",
			"invocation": [
				{
					"title": "Invocation 1",
					"argv": [
						"hise-cli",
						"mcp",
						"search_hise",
						"--query",
						"Content.addKnob",
						"--domain",
						"api",
						"--limit",
						"3",
						"--agent"
					],
					"display": "hise-cli mcp search_hise --query Content.addKnob --domain api --limit 3 --agent"
				},
				{
					"title": "Invocation 2",
					"argv": [
						"hise-cli",
						"mcp",
						"explore_hise",
						"--query",
						"sampler",
						"--agent"
					],
					"display": "hise-cli mcp explore_hise --query sampler --agent"
				},
				{
					"title": "Invocation 3",
					"argv": [
						"hise-cli",
						"mcp",
						"resources/read",
						"--uri",
						"hise://style-guides/hisescript-style",
						"--agent"
					],
					"display": "hise-cli mcp resources/read --uri hise://style-guides/hisescript-style --agent"
				}
			],
			"notes": [
				"Use native MCP access directly when the current AI agent has the HISE MCP server installed.",
				"Use hise-cli mcp as a fallback bridge when native MCP setup is unavailable or unreliable.",
				"hise-cli mcp preserves the MCP result under the normal hise-cli JSON envelope.",
				"Use --args, --args-file, or --args-stdin for nested or complex MCP arguments.",
				"Use docs lookup before inventing HiseScript APIs, UI properties, module parameters, or LAF functions."
			],
			"antiPatterns": [
				{
					"avoid": "Guessing HiseScript APIs from JavaScript knowledge.",
					"prefer": "hise-cli mcp query_scripting_api --api-call ScriptSlider.setControlCallback --agent"
				},
				{
					"avoid": "Embedding complex nested JSON in shell arguments when it becomes hard to quote.",
					"prefer": "hise-cli mcp <tool> --args-file ./mcp-args.json --agent"
				}
			],
			"capabilities": [
				{
					"id": "mcp.tool.fields",
					"title": "Call an MCP tool with field flags",
					"purpose": "Call a HISE MCP tool using CLI-friendly flags that map to MCP arguments.",
					"command": {
						"argv": [
							"hise-cli",
							"mcp",
							"explore_hise",
							"--query",
							"sampler",
							"--agent"
						],
						"display": "hise-cli mcp explore_hise --query sampler --agent"
					},
					"tags": [
						"mcp",
						"docs",
						"tool",
						"fields"
					],
					"aliases": [
						"call hise mcp tool",
						"use mcp docs bridge",
						"search hise docs from cli"
					],
					"help": {
						"visibility": "common",
						"order": 10
					},
					"examples": [
						{
							"title": "Explore sampler concepts",
							"argv": [
								"hise-cli",
								"mcp",
								"explore_hise",
								"--query",
								"sampler",
								"--agent"
							],
							"display": "hise-cli mcp explore_hise --query sampler --agent"
						},
						{
							"title": "Search for an API method",
							"argv": [
								"hise-cli",
								"mcp",
								"search_hise",
								"--query",
								"Content.addKnob",
								"--domain",
								"api",
								"--limit",
								"3",
								"--agent"
							],
							"display": "hise-cli mcp search_hise --query Content.addKnob --domain api --limit 3 --agent"
						}
					]
				},
				{
					"id": "mcp.tool.json",
					"title": "Call an MCP tool with exact JSON arguments",
					"purpose": "Call a HISE MCP tool with exact JSON arguments for complex or nested inputs.",
					"command": {
						"argv": [
							"hise-cli",
							"mcp",
							"explore_hise",
							"--args",
							"{\"query\":\"sampler\",\"source\":\"docs\"}",
							"--agent"
						],
						"display": "hise-cli mcp explore_hise --args \"{\\\"query\\\":\\\"sampler\\\",\\\"source\\\":\\\"docs\\\"}\" --agent"
					},
					"tags": [
						"mcp",
						"docs",
						"json",
						"passthrough"
					],
					"aliases": [
						"exact mcp args",
						"mcp json arguments",
						"pass json to mcp tool"
					],
					"help": {
						"visibility": "common",
						"order": 20
					},
					"examples": [
						{
							"title": "Explore docs only",
							"argv": [
								"hise-cli",
								"mcp",
								"explore_hise",
								"--args",
								"{\"query\":\"sampler\",\"source\":\"docs\"}",
								"--agent"
							],
							"display": "hise-cli mcp explore_hise --args \"{\\\"query\\\":\\\"sampler\\\",\\\"source\\\":\\\"docs\\\"}\" --agent"
						}
					]
				},
				{
					"id": "mcp.raw.method",
					"title": "Call a raw MCP method",
					"purpose": "Call raw MCP methods such as resources/list, resources/read, tools/list, or prompts/list.",
					"command": {
						"argv": [
							"hise-cli",
							"mcp",
							"resources/read",
							"--uri",
							"hise://style-guides/hisescript-style",
							"--agent"
						],
						"display": "hise-cli mcp resources/read --uri hise://style-guides/hisescript-style --agent"
					},
					"tags": [
						"mcp",
						"resources",
						"prompts",
						"methods"
					],
					"aliases": [
						"read mcp resource",
						"list mcp tools",
						"call mcp method"
					],
					"help": {
						"visibility": "common",
						"order": 30
					},
					"examples": [
						{
							"title": "List MCP tools",
							"argv": [
								"hise-cli",
								"mcp",
								"tools/list",
								"--agent"
							],
							"display": "hise-cli mcp tools/list --agent"
						},
						{
							"title": "Read HiseScript style guide",
							"argv": [
								"hise-cli",
								"mcp",
								"resources/read",
								"--uri",
								"hise://style-guides/hisescript-style",
								"--agent"
							],
							"display": "hise-cli mcp resources/read --uri hise://style-guides/hisescript-style --agent"
						}
					]
				},
				{
					"id": "mcp.search.docs",
					"title": "Search HISE documentation",
					"purpose": "Search HISE docs by keyword, API symbol, module type, UI component, or scriptnode concept.",
					"command": {
						"argv": [
							"hise-cli",
							"mcp",
							"search_hise",
							"--query",
							"Content.addKnob",
							"--domain",
							"api",
							"--limit",
							"3",
							"--agent"
						],
						"display": "hise-cli mcp search_hise --query Content.addKnob --domain api --limit 3 --agent"
					},
					"tags": [
						"mcp",
						"docs",
						"search",
						"api"
					],
					"aliases": [
						"search hise docs",
						"find hise api docs",
						"lookup hise documentation"
					],
					"help": {
						"visibility": "common",
						"order": 40
					},
					"examples": [
						{
							"title": "Search API docs",
							"argv": [
								"hise-cli",
								"mcp",
								"search_hise",
								"--query",
								"Content.addKnob",
								"--domain",
								"api",
								"--limit",
								"3",
								"--agent"
							],
							"display": "hise-cli mcp search_hise --query Content.addKnob --domain api --limit 3 --agent"
						}
					]
				},
				{
					"id": "mcp.explore.semantic",
					"title": "Explore HISE concepts semantically",
					"purpose": "Use semantic HISE docs discovery when you do not know the exact API class or method.",
					"command": {
						"argv": [
							"hise-cli",
							"mcp",
							"explore_hise",
							"--query",
							"create slider callback",
							"--domain",
							"ui",
							"--source",
							"docs",
							"--timeout",
							"180",
							"--agent"
						],
						"display": "hise-cli mcp explore_hise --query \"create slider callback\" --domain ui --source docs --timeout 180 --agent"
					},
					"tags": [
						"mcp",
						"docs",
						"semantic",
						"explore"
					],
					"aliases": [
						"semantic hise search",
						"explore hise concepts",
						"find the right hise class"
					],
					"help": {
						"visibility": "common",
						"order": 50
					},
					"examples": [
						{
							"title": "Explore slider callbacks",
							"argv": [
								"hise-cli",
								"mcp",
								"explore_hise",
								"--query",
								"create slider callback",
								"--domain",
								"ui",
								"--source",
								"docs",
								"--timeout",
								"180",
								"--agent"
							],
							"display": "hise-cli mcp explore_hise --query \"create slider callback\" --domain ui --source docs --timeout 180 --agent"
						}
					],
					"notes": [
						"The first semantic call can be slower if the MCP server is warming up an embedding model."
					]
				},
				{
					"id": "mcp.query.api",
					"title": "Query exact HiseScript API details",
					"purpose": "Get exact method signatures, parameter details, examples, and pitfalls for a HiseScript API class or method.",
					"command": {
						"argv": [
							"hise-cli",
							"mcp",
							"query_scripting_api",
							"--api-call",
							"ScriptSlider.setControlCallback",
							"--agent"
						],
						"display": "hise-cli mcp query_scripting_api --api-call ScriptSlider.setControlCallback --agent"
					},
					"tags": [
						"mcp",
						"api",
						"hissescript",
						"docs"
					],
					"aliases": [
						"query hise api method",
						"get hise method signature",
						"verify hise api call"
					],
					"help": {
						"visibility": "common",
						"order": 60
					},
					"examples": [
						{
							"title": "Query setControlCallback",
							"argv": [
								"hise-cli",
								"mcp",
								"query_scripting_api",
								"--api-call",
								"ScriptSlider.setControlCallback",
								"--agent"
							],
							"display": "hise-cli mcp query_scripting_api --api-call ScriptSlider.setControlCallback --agent"
						}
					]
				},
				{
					"id": "mcp.tui.mode",
					"title": "Use interactive MCP mode",
					"purpose": "Enter /mcp TUI mode and call MCP tools with a concise first-token command syntax.",
					"command": {
						"argv": [
							"hise-cli",
							"-mcp",
							"explore_hise",
							"sampler",
							"--agent"
						],
						"display": "hise-cli -mcp explore_hise sampler --agent"
					},
					"tags": [
						"mcp",
						"tui",
						"docs",
						"interactive"
					],
					"aliases": [
						"mcp tui mode",
						"interactive hise docs mode",
						"slash mcp mode"
					],
					"help": {
						"visibility": "common",
						"order": 70
					},
					"examples": [
						{
							"title": "Explore sampler in TUI mode syntax",
							"argv": [
								"hise-cli",
								"-mcp",
								"explore_hise",
								"sampler",
								"--agent"
							],
							"display": "hise-cli -mcp explore_hise sampler --agent"
						}
					],
					"notes": [
						"In TUI mode, autocomplete and syntax highlighting apply only to the first token.",
						"Text and resource responses render as markdown for humans."
					]
				}
			]
		},
		{
			"id": "script",
			"title": "HiseScript REPL and callback editing",
			"summary": "Evaluate HiseScript expressions and read or update script callbacks without shell-quoting callback bodies.",
			"invocation": [
				{
					"title": "Invocation 1",
					"argv": [
						"hise-cli",
						"script",
						"repl",
						"--module-id",
						"Interface",
						"--stdin",
						"--agent"
					],
					"display": "hise-cli script repl --module-id Interface --stdin --agent"
				},
				{
					"title": "Invocation 2",
					"argv": [
						"hise-cli",
						"script",
						"get",
						"--module-id",
						"Interface",
						"--callback",
						"onInit",
						"--agent"
					],
					"display": "hise-cli script get --module-id Interface --callback onInit --agent"
				},
				{
					"title": "Invocation 3",
					"argv": [
						"hise-cli",
						"script",
						"set",
						"--module-id",
						"Interface",
						"--callback",
						"onInit",
						"--file",
						"./onInit.js",
						"--agent"
					],
					"display": "hise-cli script set --module-id Interface --callback onInit --file ./onInit.js --agent"
				}
			],
			"notes": [
				"Prefer stdin or file inputs for script bodies.",
				"script set compiles by default; use --no-compile to skip compilation.",
				"--module-id defaults to Interface.",
				"REPL evaluation cannot create persistent declarations in the script engine. Do not use it to add variables, functions, callbacks, includes, or other durable script source.",
				"Use REPL only for read-only queries and explicit calls to existing functions or APIs. Those calls may still have side effects.",
				"For persistent script source changes, use script set with --stdin, --file, or --callbacks-json.",
				"If a task has a dedicated hise-cli mode, use that mode instead of mutating state through REPL-side HiseScript.",
				"Keep callbacks thin in real projects. onInit should usually include external files rather than contain large inline implementations, so those files can be checked with script diagnose before compilation.",
				"Prefer component-specific control callbacks using Component.setControlCallback(f) over a large global onControl dispatcher. HISE requires f to be an inline function reference with signature (component, value)."
			],
			"antiPatterns": [
				{
					"avoid": "Passing callback bodies as inline shell arguments.",
					"prefer": "hise-cli script set --module-id Interface --callback onInit --stdin --agent"
				},
				{
					"avoid": "Using legacy quoted REPL expressions for multi-line scripts.",
					"prefer": "hise-cli script repl --module-id Interface --stdin --agent"
				},
				{
					"avoid": "Trying to declare persistent variables, functions, callbacks, or includes via REPL.",
					"prefer": "hise-cli script set --module-id Interface --callback onInit --file ./onInit.js --agent"
				},
				{
					"avoid": "Using REPL-side HiseScript to perform UI edits when the UI mode supports the operation.",
					"prefer": "hise-cli -ui set Button1.text \"my text\" --agent"
				},
				{
					"avoid": "Putting large implementation bodies directly into onInit.",
					"prefer": "Keep onInit small and include external script files that can be edited and diagnosed separately with script diagnose."
				},
				{
					"avoid": "Building a large global onControl dispatcher or passing an anonymous regular function to setControlCallback.",
					"prefer": "Define an inline function f(component, value) and assign it with Component.setControlCallback(f)."
				},
				{
					"avoid": "Repeatedly compiling external script edits to discover one error at a time.",
					"prefer": "Run hise-cli script diagnose --file-path Scripts/UI.js --agent before compiling."
				}
			],
			"capabilities": [
				{
					"id": "script.repl.stdin",
					"title": "Evaluate REPL expression from stdin",
					"purpose": "Evaluate a HiseScript expression using stdin so callers avoid shell quoting issues.",
					"command": {
						"argv": [
							"hise-cli",
							"script",
							"repl",
							"--module-id",
							"Interface",
							"--stdin",
							"--agent"
						],
						"display": "hise-cli script repl --module-id Interface --stdin --agent"
					},
					"tags": [
						"script",
						"repl",
						"stdin",
						"expression"
					],
					"aliases": [
						"run hise script expression",
						"evaluate hise script",
						"repl from stdin"
					],
					"help": {
						"visibility": "common",
						"order": 10
					},
					"examples": [
						{
							"title": "Read the sample rate",
							"argv": [
								"hise-cli",
								"script",
								"repl",
								"--module-id",
								"Interface",
								"--stdin",
								"--agent"
							],
							"display": "hise-cli script repl --module-id Interface --stdin --agent",
							"stdin": "Engine.getSampleRate()"
						}
					],
					"notes": [
						"REPL evaluation cannot create persistent declarations in the script engine.",
						"Use REPL for read-only queries and explicit calls to existing functions or APIs. Those calls may still have side effects.",
						"Prefer dedicated hise-cli modes for UI, builder, DSP, project, or asset changes when available."
					]
				},
				{
					"id": "script.get.callback",
					"title": "Get one script callback",
					"purpose": "Read one callback from a script processor.",
					"command": {
						"argv": [
							"hise-cli",
							"script",
							"get",
							"--module-id",
							"Interface",
							"--callback",
							"onInit",
							"--agent"
						],
						"display": "hise-cli script get --module-id Interface --callback onInit --agent"
					},
					"tags": [
						"script",
						"callback",
						"get",
						"read"
					],
					"aliases": [
						"read onInit",
						"get callback",
						"show callback source"
					],
					"help": {
						"visibility": "common",
						"order": 20
					},
					"examples": [
						{
							"title": "Read onInit",
							"argv": [
								"hise-cli",
								"script",
								"get",
								"--module-id",
								"Interface",
								"--callback",
								"onInit",
								"--agent"
							],
							"display": "hise-cli script get --module-id Interface --callback onInit --agent"
						},
						{
							"title": "Read onControl",
							"argv": [
								"hise-cli",
								"script",
								"get",
								"--module-id",
								"Interface",
								"--callback",
								"onControl",
								"--agent"
							],
							"display": "hise-cli script get --module-id Interface --callback onControl --agent"
						}
					]
				},
				{
					"id": "script.get.all",
					"title": "Get all script callbacks",
					"purpose": "Read all callbacks and external file references for a script processor.",
					"command": {
						"argv": [
							"hise-cli",
							"script",
							"get",
							"--module-id",
							"Interface",
							"--agent"
						],
						"display": "hise-cli script get --module-id Interface --agent"
					},
					"tags": [
						"script",
						"callback",
						"get",
						"read",
						"all"
					],
					"aliases": [
						"list callbacks",
						"get all callbacks",
						"show script callbacks"
					],
					"help": {
						"visibility": "common",
						"order": 30
					},
					"examples": [
						{
							"title": "Read all callbacks",
							"argv": [
								"hise-cli",
								"script",
								"get",
								"--module-id",
								"Interface",
								"--agent"
							],
							"display": "hise-cli script get --module-id Interface --agent"
						}
					]
				},
				{
					"id": "script.set.callback.stdin",
					"title": "Set script callback from stdin",
					"purpose": "Update one callback from stdin and compile by default.",
					"command": {
						"argv": [
							"hise-cli",
							"script",
							"set",
							"--module-id",
							"Interface",
							"--callback",
							"onInit",
							"--stdin",
							"--agent"
						],
						"display": "hise-cli script set --module-id Interface --callback onInit --stdin --agent"
					},
					"tags": [
						"script",
						"callback",
						"set",
						"stdin",
						"compile"
					],
					"aliases": [
						"edit onInit from stdin",
						"update callback from stdin",
						"set callback body"
					],
					"help": {
						"visibility": "common",
						"order": 40
					},
					"examples": [
						{
							"title": "Replace onInit from stdin",
							"argv": [
								"hise-cli",
								"script",
								"set",
								"--module-id",
								"Interface",
								"--callback",
								"onInit",
								"--stdin",
								"--agent"
							],
							"display": "hise-cli script set --module-id Interface --callback onInit --stdin --agent",
							"stdin": "Content.makeFrontInterface(600, 600);\nConsole.print(\"ready\");"
						}
					],
					"notes": [
						"Use --no-compile when staging callback changes without recompilation."
					]
				},
				{
					"id": "script.set.callback.file",
					"title": "Set script callback from file",
					"purpose": "Update one callback from a file and compile by default.",
					"command": {
						"argv": [
							"hise-cli",
							"script",
							"set",
							"--module-id",
							"Interface",
							"--callback",
							"onInit",
							"--file",
							"./onInit.js",
							"--agent"
						],
						"display": "hise-cli script set --module-id Interface --callback onInit --file ./onInit.js --agent"
					},
					"tags": [
						"script",
						"callback",
						"set",
						"file",
						"compile"
					],
					"aliases": [
						"edit onInit from file",
						"update callback from file",
						"load callback file"
					],
					"help": {
						"visibility": "common",
						"order": 50
					},
					"examples": [
						{
							"title": "Replace onInit from a file",
							"argv": [
								"hise-cli",
								"script",
								"set",
								"--module-id",
								"Interface",
								"--callback",
								"onInit",
								"--file",
								"./onInit.js",
								"--agent"
							],
							"display": "hise-cli script set --module-id Interface --callback onInit --file ./onInit.js --agent"
						}
					],
					"notes": [
						"This is the preferred path for multi-line callback edits."
					]
				},
				{
					"id": "script.set.callbacks-json",
					"title": "Set multiple callbacks from JSON",
					"purpose": "Update multiple callbacks from a JSON file and compile by default.",
					"command": {
						"argv": [
							"hise-cli",
							"script",
							"set",
							"--module-id",
							"Interface",
							"--callbacks-json",
							"./callbacks.json",
							"--agent"
						],
						"display": "hise-cli script set --module-id Interface --callbacks-json ./callbacks.json --agent"
					},
					"tags": [
						"script",
						"callback",
						"set",
						"json",
						"compile"
					],
					"aliases": [
						"update multiple callbacks",
						"set callbacks json",
						"load callbacks from json"
					],
					"help": {
						"visibility": "common",
						"order": 60
					},
					"examples": [
						{
							"title": "Replace callbacks from JSON",
							"argv": [
								"hise-cli",
								"script",
								"set",
								"--module-id",
								"Interface",
								"--callbacks-json",
								"./callbacks.json",
								"--agent"
							],
							"display": "hise-cli script set --module-id Interface --callbacks-json ./callbacks.json --agent"
						}
					]
				},
				{
					"id": "script.compile",
					"title": "Compile script processor",
					"purpose": "Recompile a script processor after editing callback or external script files.",
					"command": {
						"argv": [
							"hise-cli",
							"script",
							"compile",
							"--module-id",
							"Interface",
							"--agent"
						],
						"display": "hise-cli script compile --module-id Interface --agent"
					},
					"tags": [
						"script",
						"compile",
						"recompile"
					],
					"aliases": [
						"recompile script",
						"compile Interface",
						"rerun initialization code"
					],
					"help": {
						"visibility": "common",
						"order": 70
					},
					"examples": [
						{
							"title": "Compile Interface",
							"argv": [
								"hise-cli",
								"script",
								"compile",
								"--module-id",
								"Interface",
								"--agent"
							],
							"display": "hise-cli script compile --module-id Interface --agent"
						}
					]
				},
				{
					"id": "script.diagnose",
					"title": "Diagnose script source",
					"purpose": "Run HISE shadow-parser diagnostics without recompiling or executing script code.",
					"command": {
						"argv": [
							"hise-cli",
							"script",
							"diagnose",
							"--module-id",
							"Interface",
							"--agent"
						],
						"display": "hise-cli script diagnose --module-id Interface --agent"
					},
					"tags": [
						"script",
						"diagnose",
						"diagnostics",
						"validation",
						"shadow-parser"
					],
					"aliases": [
						"shadow parse script",
						"multi error diagnostics",
						"validate script file",
						"diagnose onInit"
					],
					"help": {
						"visibility": "common",
						"order": 80
					},
					"examples": [
						{
							"title": "Diagnose Interface script processor",
							"argv": [
								"hise-cli",
								"script",
								"diagnose",
								"--module-id",
								"Interface",
								"--agent"
							],
							"display": "hise-cli script diagnose --module-id Interface --agent"
						},
						{
							"title": "Diagnose an external script file",
							"argv": [
								"hise-cli",
								"script",
								"diagnose",
								"--file-path",
								"Scripts/UI.js",
								"--agent"
							],
							"display": "hise-cli script diagnose --file-path Scripts/UI.js --agent"
						}
					],
					"notes": [
						"Requires at least one prior successful compile.",
						"Always reads the file from disk; save pending edits before calling.",
						"Diagnostics with severity error return validation_error and exit code 5.",
						"When editing external script files, run script diagnose before compiling unless the edit is small and you are confident it compiles.",
						"The normal HISE compiler is fail-fast; diagnose can report multiple errors at once and can catch issues that would otherwise surface only at runtime."
					]
				},
				{
					"id": "script.show.tree",
					"title": "Show compiled script symbol tree",
					"purpose": "Inspect the currently compiled script symbol hierarchy with server-side filtering options.",
					"command": {
						"argv": [
							"hise-cli",
							"script",
							"show",
							"tree",
							"--module-id",
							"Interface",
							"--symbols-only",
							"--agent"
						],
						"display": "hise-cli script show tree --module-id Interface --symbols-only --agent"
					},
					"tags": [
						"script",
						"symbols",
						"tree",
						"inspect",
						"compiled"
					],
					"aliases": [
						"show script tree",
						"inspect script symbols",
						"list script variables",
						"compiled symbol tree"
					],
					"help": {
						"visibility": "common",
						"order": 90
					},
					"examples": [
						{
							"title": "Show a cheap symbol overview",
							"argv": [
								"hise-cli",
								"script",
								"show",
								"tree",
								"--module-id",
								"Interface",
								"--symbols-only",
								"--agent"
							],
							"display": "hise-cli script show tree --module-id Interface --symbols-only --agent"
						},
						{
							"title": "Search symbols server-side",
							"argv": [
								"hise-cli",
								"script",
								"show",
								"tree",
								"Knob",
								"--module-id",
								"Interface",
								"--format",
								"flat",
								"--limit",
								"20",
								"--agent"
							],
							"display": "hise-cli script show tree Knob --module-id Interface --format flat --limit 20 --agent"
						}
					],
					"notes": [
						"The symbol tree reflects the last compiled script model; compile after source edits before relying on it.",
						"Use --symbols-only for first-pass discovery. It preserves expression and dataType while omitting value and location.",
						"Use positional search or --search to filter on the HISE side and avoid large JSON responses."
					]
				},
				{
					"id": "script.show.symbol",
					"title": "Show one script symbol",
					"purpose": "Inspect one compiled script symbol and include available API methods for its data type when known.",
					"command": {
						"argv": [
							"hise-cli",
							"script",
							"show",
							"Components.Knob1",
							"--module-id",
							"Interface",
							"--agent"
						],
						"display": "hise-cli script show Components.Knob1 --module-id Interface --agent"
					},
					"tags": [
						"script",
						"symbols",
						"inspect",
						"methods",
						"api"
					],
					"aliases": [
						"show available methods on knob",
						"inspect script variable",
						"show symbol methods",
						"inspect component reference"
					],
					"help": {
						"visibility": "common",
						"order": 100
					},
					"examples": [
						{
							"title": "Inspect a component reference",
							"argv": [
								"hise-cli",
								"script",
								"show",
								"Components.Knob1",
								"--module-id",
								"Interface",
								"--agent"
							],
							"display": "hise-cli script show Components.Knob1 --module-id Interface --agent"
						}
					],
					"notes": [
						"Discover expressions first with script show tree --symbols-only.",
						"API method enrichment uses the symbol dataType from the compiled script model.",
						"The api.methods list contains fully qualified API expressions such as ScriptSlider.setControlCallback; pass one to hise-cli -api for full method documentation."
					]
				},
				{
					"id": "script.legacy.repl",
					"title": "Legacy one-shot REPL expression",
					"purpose": "Evaluate a short HiseScript expression using the legacy mode form.",
					"command": {
						"argv": [
							"hise-cli",
							"-script",
							"Engine.getSampleRate()",
							"--agent"
						],
						"display": "hise-cli -script \"Engine.getSampleRate()\" --agent"
					},
					"tags": [
						"script",
						"repl",
						"legacy"
					],
					"aliases": [
						"legacy script expression",
						"one shot script expression"
					],
					"help": {
						"visibility": "hidden",
						"order": 100
					},
					"notes": [
						"Accepted for short expressions, but stdin is preferred for agent workflows."
					]
				}
			]
		}
	]
} as const satisfies AgentContextData;
